import { useState, useEffect, useRef } from 'react';
import { useParams, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowLeft, Plus, Clock, CheckCircle, RefreshCw, FileDown } from 'lucide-react';
import { TakaIcon } from '@/components/TakaIcon';
import { Layout } from '@/components/Layout';
import { StatCard } from '@/components/StatCard';
import { MonthYearFilter } from '@/components/MonthYearFilter';
import { SalaryTable } from '@/components/SalaryTable';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useShop } from '@/hooks/useShops';
import { useEmployees } from '@/hooks/useEmployees';
import { useSalaryRecords, useShopPayrollSummary, useGenerateSalaryRecords } from '@/hooks/useSalaryRecords';
import { supabase } from '@/integrations/supabase/client';
import type { LeaveEntry } from '@/lib/types';
import { formatCurrency, getMonthName, calculateSalary } from '@/lib/types';
import { exportSalarySheetPdf } from '@/lib/exportSalarySheetPdf';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';

export default function ShopSalarySheet() {
  const { shopId } = useParams<{ shopId: string }>();
  const currentDate = new Date();
  const [month, setMonth] = useState(currentDate.getMonth() + 1);
  const [year, setYear] = useState(currentDate.getFullYear());
  const [isExportingPdf, setIsExportingPdf] = useState(false);
  const [exportPdfOpen, setExportPdfOpen] = useState(false);
  const [selectedRecordId, setSelectedRecordId] = useState<string>('');
  const autoGeneratedKey = useRef<string | null>(null);

  const { data: shop, isLoading: shopLoading } = useShop(shopId || '');
  const { data: employees } = useEmployees(shopId || undefined);
  const { data: records, isLoading: recordsLoading } = useSalaryRecords(shopId, month, year);
  const { data: summaryFromApi } = useShopPayrollSummary(shopId || '', month, year);
  const generateRecords = useGenerateSalaryRecords();

  // Derive summary from records; Total Paid = salary disbursed (status=Paid) + advance already given
  const summary =
    records && records.length > 0
      ? records.reduce(
          (acc, r) => {
            const base = Number(r.employee?.base_salary ?? 0);
            const days = 30; // attendance always 30 days per month
            const total = calculateSalary(
              base,
              r.attendance_days,
              Number(r.paid_leave ?? 0),
              Number(r.bonus ?? 0),
              Number(r.increment_adjustment ?? 0),
              Number(r.advance_taken ?? 0),
              Number(r.penalty ?? 0),
              days
            );
            const advance = Number(r.advance_taken ?? 0);
            acc.totalPayroll += total;
            if (r.status === 'Paid') acc.totalPaid += total;
            else acc.totalPending += total;
            acc.totalAdvance += advance; // advance = money already given to employees
            return acc;
          },
          { totalPayroll: 0, totalPaid: 0, totalPending: 0, totalAdvance: 0 }
        )
      : summaryFromApi;

  // Auto-generate salary records when shop has employees but no records for this month/year
  useEffect(() => {
    const key = `${shopId}-${month}-${year}`;
    if (
      shopId &&
      !recordsLoading &&
      (records?.length ?? 0) === 0 &&
      (employees?.length ?? 0) > 0 &&
      !generateRecords.isPending &&
      autoGeneratedKey.current !== key
    ) {
      autoGeneratedKey.current = key;
      generateRecords.mutate({ shopId, month, year });
    }
  }, [shopId, month, year, records?.length, recordsLoading, employees?.length, generateRecords.isPending]);

  const isClassio = shop?.name === 'Classio';
  const gradientClass = isClassio ? 'gradient-classio' : 'gradient-goodvibes';

  const handleGenerate = () => {
    if (shopId) {
      generateRecords.mutate({ shopId, month, year });
    }
  };

  /** Export PDF for all employees or a single record (recordId). */
  const handleExportPdf = async (recordId?: string) => {
    if (!shop?.name) return;
    const list = records ?? [];
    if (list.length === 0) return;
    const toExport = recordId ? list.filter((r) => r.id === recordId) : list;
    if (toExport.length === 0) return;
    setIsExportingPdf(true);
    try {
      const recordIds = toExport.map((r) => r.id);
      const { data: leaveRows } = await supabase
        .from('leave_entries')
        .select('*')
        .in('salary_record_id', recordIds)
        .order('leave_date', { ascending: true });
      const leaveEntriesMap: Record<string, LeaveEntry[]> = {};
      for (const row of leaveRows ?? []) {
        const rec = row as LeaveEntry;
        if (!leaveEntriesMap[rec.salary_record_id]) leaveEntriesMap[rec.salary_record_id] = [];
        leaveEntriesMap[rec.salary_record_id].push(rec);
      }
      const employeeName = toExport.length === 1 ? toExport[0].employee?.name : undefined;
      exportSalarySheetPdf(shop.name, month, year, toExport, leaveEntriesMap, employeeName);
      toast.success(toExport.length === 1 ? 'Employee salary sheet downloaded' : 'Salary sheet PDF downloaded');
      setExportPdfOpen(false);
      setSelectedRecordId('');
    } finally {
      setIsExportingPdf(false);
    }
  };

  if (shopLoading) {
    return (
      <Layout>
        <div className="flex items-center justify-center py-20">
          <div className="h-10 w-10 animate-spin rounded-full border-4 border-primary border-t-transparent" />
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="space-y-8">
        {/* Header */}
        <div className="flex flex-col gap-4">
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors w-fit"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Dashboard
          </Link>

          <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between min-w-0">
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              className="min-w-0"
            >
              <div className="flex items-center gap-2 sm:gap-3 min-w-0">
                <div className={cn('h-10 w-10 sm:h-12 sm:w-12 shrink-0 rounded-xl flex items-center justify-center', gradientClass)}>
                  <TakaIcon className="h-5 w-5 sm:h-6 sm:w-6 text-white" />
                </div>
                <div className="min-w-0">
                  <h1 className="text-xl sm:text-2xl md:text-3xl font-bold break-words">{shop?.name}</h1>
                  <p className="text-sm text-muted-foreground">
                    Salary Sheet for {getMonthName(month)} {year}
                  </p>
                </div>
              </div>
            </motion.div>

            <div className="flex flex-wrap items-center gap-2 sm:gap-3 w-full sm:w-auto">
              <MonthYearFilter
                month={month}
                year={year}
                onMonthChange={setMonth}
                onYearChange={setYear}
              />
              <Dialog open={exportPdfOpen} onOpenChange={setExportPdfOpen}>
                <Button
                  variant="outline"
                  disabled={!shop?.name || (records?.length ?? 0) === 0}
                  className="gap-2 min-h-touch w-full sm:w-auto"
                  onClick={() => setExportPdfOpen(true)}
                >
                  <FileDown className="h-4 w-4 shrink-0" />
                  <span className="truncate">Export PDF</span>
                </Button>
                <DialogContent className="sm:max-w-md">
                  <DialogHeader>
                    <DialogTitle>Export salary sheet</DialogTitle>
                    <DialogDescription>
                      Export the full sheet (all employees) or choose one employee to export their salary sheet only.
                    </DialogDescription>
                  </DialogHeader>
                  <div className="flex flex-col gap-4 py-2">
                    <Button
                      onClick={() => handleExportPdf()}
                      disabled={isExportingPdf}
                      className="w-full gap-2"
                      variant="default"
                    >
                      {isExportingPdf ? (
                        <RefreshCw className="h-4 w-4 animate-spin" />
                      ) : (
                        <FileDown className="h-4 w-4" />
                      )}
                      Export all employees
                    </Button>
                    <div className="relative">
                      <div className="absolute inset-0 flex items-center">
                        <span className="w-full border-t" />
                      </div>
                      <div className="relative flex justify-center text-xs uppercase">
                        <span className="bg-background px-2 text-muted-foreground">Or</span>
                      </div>
                    </div>
                    <div className="space-y-2">
                      <label className="text-sm font-medium">Export one employee (by ID)</label>
                      <Select
                        value={selectedRecordId}
                        onValueChange={setSelectedRecordId}
                        disabled={isExportingPdf}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select by employee ID" />
                        </SelectTrigger>
                        <SelectContent>
                          {(records ?? [])
                            .slice()
                            .sort((a, b) => {
                              const idA = a.employee?.employee_id ?? '';
                              const idB = b.employee?.employee_id ?? '';
                              return idA.localeCompare(idB, undefined, { numeric: true });
                            })
                            .map((r) => (
                              <SelectItem key={r.id} value={r.id}>
                                {r.employee?.employee_id ?? '—'} — {r.employee?.name ?? 'Unknown'}
                              </SelectItem>
                            ))}
                        </SelectContent>
                      </Select>
                      <Button
                        onClick={() => handleExportPdf(selectedRecordId)}
                        disabled={!selectedRecordId || isExportingPdf}
                        variant="outline"
                        className="w-full gap-2"
                      >
                        {isExportingPdf ? (
                          <RefreshCw className="h-4 w-4 animate-spin" />
                        ) : (
                          <FileDown className="h-4 w-4" />
                        )}
                        Export selected employee
                      </Button>
                    </div>
                  </div>
                  <DialogFooter className="sm:justify-start">
                    <Button type="button" variant="ghost" onClick={() => setExportPdfOpen(false)}>
                      Cancel
                    </Button>
                  </DialogFooter>
                </DialogContent>
              </Dialog>
              <Button
                onClick={handleGenerate}
                disabled={generateRecords.isPending}
                className={cn(gradientClass, 'text-white border-0 min-h-touch w-full sm:w-auto')}
              >
                {generateRecords.isPending ? (
                  <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                ) : (
                  <Plus className="h-4 w-4 mr-2" />
                )}
                Generate Records
              </Button>
            </div>
          </div>
        </div>

        {/* Stats - Paid = disbursed + advance already given */}
        <div className="grid gap-4 md:grid-cols-3">
          <StatCard
            title="Total Payroll"
            value={formatCurrency(summary?.totalPayroll || 0)}
            icon={TakaIcon}
            variant="primary"
            delay={0}
          />
          <StatCard
            title="Paid"
            value={formatCurrency((summary?.totalPaid ?? 0) + (summary && 'totalAdvance' in summary ? summary.totalAdvance : 0))}
            subtitle="Disbursed + advance given"
            icon={CheckCircle}
            variant="success"
            delay={0.1}
          />
          <StatCard
            title="Pending"
            value={formatCurrency(summary?.totalPending || 0)}
            icon={Clock}
            variant="warning"
            delay={0.2}
          />
        </div>

        {/* Salary Table */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
        >
          <SalaryTable
            records={(records || []) as any}
            isLoading={recordsLoading}
            month={month}
            year={year}
          />
        </motion.div>
      </div>
    </Layout>
  );
}
